title: NLP Researcher
subtitle: study for NLP
description: >-
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is
  optimized for speed and readability.
url: 'https://inhukim.github.io/'
baseurl: ''
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery

author_logo: profile.png
author: Inhu Kim
author_bio: 'Hi, my name is Inhu Kim :D'
author_email: markaki72@gmail.com
author_location: Korea
typewrite-text: NLP 관련 개발에 관심
hero_cover_img: sample_cover.jpg
author_work_experiences: null
author_education_details: null
author_project_details: null
github_username: InhuKim
#hyvor_talk_website_id: 476
formspree_email: markaki72@gmail.com
olvy_organization: devlopr
olvy_widget_type: sidebar
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: false
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  products:
    output: 'False'
  authors: {}
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      permalink: '/blog/authors/:slug'
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
jekyll_admin:
  homepage: posts
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
